### ISSUE TITLE
Chromium 33: TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by MorganBorman** [bgschiller/highlight-world-map#2]
On Chromium 33 I get a blank page on submit with an error in the console;
Uncaught TypeError: Cannot read property '0' of undefined highlight-world-map.js:10
isHexColor highlight-world-map.js:10
(anonymous function) highlight-world-map.js:162

Repro steps: (happens all the time, but here's what I did)
- Type "Brazil"
- Click on Brazil the drop down
- Click submit

**Comment by bgschiller** [comment]
I couldn't reproduce this on Chromium 33 running on OS X. I'll try switching to windows. You're on Ubuntu?

**Comment by bgschiller** [comment]
Couldn't reproduce on Windows with Chromium 33 either.

**Comment by MorganBorman** [comment]
Seems to be working for me now. Not sure what changed.
